### ISSUE TITLE
Ex. 5.6 clarification

### ISSUE THREAD

**Issue by andrewpbray** [mdsr-book/mdsr-book.github.io#10]
"Verify that this code works..."

Many students interpreted this as needing to run the code. Was this your intent? If it was, where can they find the data set?

**Comment by beanumber** [comment]
I think that was not the intent. @nicholasjhorton can you clarify? 

In any case, here is the data:
```
ds1 <- data_frame(id=c(1:3, 1:3), group=c(rep("T", 3), rep("C", 3)), vals=c(4,6,8,5,6,10))
```

**Comment by andrewpbray** [comment]
A similar question arises in 5.7. Do you expect students to just sketch out their operations but not run the code or expect them to type in this data set? Also, is `unite()` covered in this chapter?

**Comment by beanumber** [comment]
* @nicholasjhorton to confirm that these are pencil-and-paper exercises
* I don't think we cover `unite()`. Do you use it? 
* Ah...the argument names are omitted in the solution code. This should make it clearer:
```
transformed <- sumdf %>%
  gather(key = "temp", value = "vals", meanL, meanR, sdL, sdR) %>%
  unite(col = "temp1", sex, temp, sep = ".") %>%
  spread(temp1, vals)
```
Oh, now I see why you are asking about `unite()`. 

Any wisdom @nicholasjhorton ?

**Comment by nicholasjhorton** [comment]
Do you have the answer key for this problem?  I worry that it may not be included in the version that John distributed.


> On Mar 1, 2017, at 4:50 PM, Andrew Bray <notifications@github.com> wrote:
> 
> A similar question arises in 5.7. Do you expect students to just sketch out their operations but not run the code or expect them to type in this data set? Also, is unite() covered in this chapter?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by nicholasjhorton** [comment]
<img width="734" alt="screen shot 2017-03-02 at 11 26 55 am" src="https://cloud.githubusercontent.com/assets/530542/23516437/33da8ff8-ff3b-11e6-8480-23cca9b3f2d5.png">
<img width="698" alt="screen shot 2017-03-02 at 11 27 29 am" src="https://cloud.githubusercontent.com/assets/530542/23516458/40d02498-ff3b-11e6-896b-e82db5eb39f0.png">

**Comment by andrewpbray** [comment]
This looks like a slightly updated version of the one that I have (I don't think mine has the data entry step for 5.6). I'm still wondering:

- Are you expecting that students will do the data entry themselves (which would mean creating the `sumdf` that is used in 5.7)?
- Is `unite()` somewhere in the text that I just am not seeing?

**Comment by nicholasjhorton** [comment]
No: unite() isn't mentioned in the chapter.  

We were intending that students have the data entry themselves.

Nick

> On Mar 2, 2017, at 12:12 PM, Andrew Bray <notifications@github.com> wrote:
> 
> This looks like a slightly updated version of the one that I have (I don't think mine has the data entry step for 5.6). I'm still wondering:
> 
> 	• Are you expecting that students will do the data entry themselves (which would mean creating the sumdf that is used in 5.7)?
> 	• Is unite() somewhere in the text that I just am not seeing?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by andrewpbray** [comment]
Ah ok, I didn't realize that about the data entry. I'll pass that along to my students.

Thanks!

**Comment by beanumber** [comment]
@nicholasjhorton is any update needed here for the 2nd edition?
