### ISSUE TITLE
tried to rebuild exercises.Rmd

### ISSUE THREAD

**Issue by nicholasjhorton** [mdsr-book/mdsr-book.github.io#11]
libs/font-awesome-4.1.0/css/font-awesome.min.css

When I tried to build the exercises.Rmd file (which has some minor changes), I got an error message that the css file wasn't available in the repo.  Can you please:

(1) render exercises.Rmd and push the exercises.html to the github webpage, and

(2) add the needed files in at some point?

**Comment by beanumber** [comment]
FYI, you may have to run `make`, rather than just try to re-knit one file.
