### ISSUE TITLE
photo for horton not displaying on authors.html

### ISSUE THREAD

**Issue by nicholasjhorton** [mdsr-book/mdsr-book.github.io#13]
Any idea what might be going on?

**Comment by beanumber** [comment]
https://github.com/mdsr-book/mdsr-book.github.io/commit/c53425ddf9e7c10df9225df63a805b3a29a64d03#diff-9b437f22543830607b829e77f7f117dc seems to be the culprit. 

The problem seems to be the ampersand in the URL. I found another URL and it works now.
