### ISSUE TITLE
Typo on page 465

### ISSUE THREAD

**Issue by alanarnholt** [mdsr-book/mdsr-book.github.io#14]
Page 465 defines the residual as $\epsilon = y_i - \hat{y}_i$...it should be $\hat{\epsilon} = y_i - \hat{y}_i$ or possibly $e_i = y_i - \hat{y}_i$.

**Comment by nicholasjhorton** [comment]
Thanks for pointing this out.

**Comment by beanumber** [comment]
@alanarnholt Nice catch!
