### ISSUE TITLE
errata with presidents

### ISSUE THREAD

**Issue by nicholasjhorton** [mdsr-book/mdsr-book.github.io#15]
I noticed a minor issue with one of the examples in “Modern Data Science with R”, pages 64-66.

Could you maybe forward this mail to Mr. Baumer, Kaplan and Horton? Or send me their email addresses so that I can contact them directly?

Regarding the problem: It’s the example from pages 64-66, where you are supposed to select all Democratic presidents since 1973. 

This is working fine. However, once you remove the condition party == Democratic, you get an incorrect result since Ford is ignored (start of presidency in 1974). My professor told me that this results from the fact that we compare a date (start of presidency) with a number (1973). Since the reference point for date integers is 01.01.1970, the date value of Ford is 1681, which is smaller than 1973 and he is ignored. Hence, the correct result would be

presidential %>%
filter(start > as.Date("1973", "%Y") ) %>%
select(name)

**Comment by beanumber** [comment]
Oh wow -- what an incredible coincidence! 

Two potentially cleaner fixes would be:
```
filter(presidential, start > "1973-01-01")
filter(presidential, lubridate::year(start) > 1973)
```
I sort of like the first one above, since of the three, it's the only one that doesn't introduce any new functions. We introduce `lubridate` two pages later. 

@nicholasjhorton what do you think?

**Comment by beanumber** [comment]
Closed via https://github.com/beanumber/mdsr2e/commit/0974769f8fffdaad5f89d3e0224cd740be4f8ad8
