### ISSUE TITLE
Two typos on page 156-157 and some text that may need to be changed.

### ISSUE THREAD

**Issue by alanarnholt** [mdsr-book/mdsr-book.github.io#16]
---
title: "Chapter 7"
author: "Modern Data Science with `R`"
date: 'Last knit: `r format(Sys.time(), "%B %d, %Y")`'
output: 
  bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", warning = FALSE, message = FALSE)
library(mdsr)
library(mosaic)
library(mosaicData)
library(nycflights13)
SF <- flights %>% 
  filter(dest == "SFO", !is.na(arr_delay))
```

## Page 156 {-}

**Note:** Without setting a seed (or maybe you have hidden code chunks?) book values are not reproducible.

Let’s use bootstrapping to find the reliability of the mean arrival time calculated on a sample of size 200.

```{r}
n <- 200
Orig_sample <- SF %>% sample_n(size = n, replace = FALSE)
```

Now, with the original sample in hand, we can draw a resample and calculate the mean arrival delay.

```{r}
mean( ~ arr_delay,
      data = sample_n(Orig_sample, size = n, replace = TRUE))
```

By repeating this process many times, we’ll be able to see how much variation there is from sample to sample:

```{r}
Bootstrap_trials <- do(500) * mean(~arr_delay,
  data = sample_n(Orig_sample, size = n, replace = TRUE))
favstats(~mean, data = Bootstrap_trials)
ggplot(data = Bootstrap_trials, aes(x = mean)) + 
  geom_histogram(fill = "pink", color = "black") + 
  theme_bw()
```

* Typo on bottom of page 156 has $n = 1000$....should be as below $n = 200$.  Note that the `Orig_sample` has $n = 200$.

We can compare this to a (hypothetical) sample of size $n = 200$ from the original `SF` flights.

```{r}
Trials_200 <- do(500) *
  mean( ~ arr_delay, data = sample_n(SF, size = 200, replace = FALSE))
favstats( ~ mean, data = Trials_200)
ggplot(data = Trials_200, aes(x = mean)) + 
  geom_histogram(fill = "pink", color = "black") + 
  theme_bw()
```

Notice that the population was not used in the bootstrap, just the original sample. What’s remarkable here is that the standard error calculated in this way, `r favstats(~mean, data = Bootstrap_trials)[7]` minutes, is a reasonable approximation to the standard error of the sampling population calculated in the previous section (`r favstats(~mean, data = Trials_200)[7]` minutes).

The distribution of values in the bootstrap trials is called the bootstrap distribution. It’s not exactly the same as the sampling distribution, but for moderate to large sample sizes it has been proven to approximate those aspects of the sampling distribution that we care most about, such as the standard error.

* The sample size below is referring to `Orig_sample` which has $n = 200$, ... although the problem was initially introduced using a sample of size $n = 100$.  I believe this makes more sense to have both be $n = 200$.  I have changed the value in the paragraph below.

Let’s return to our original example of setting a travel policy for selecting flights from New York to San Francisco. Recall that we decided to set a goal of arriving in time for the meeting 98% of the time. We can calculate the 98^_th_^ percentile from our sample of size $n = 200$ flights, and use bootstrapping to see how reliable that sample statistic is.

The sample itself suggests a policy of scheduling a flight to arrive `r qdata( ~ arr_delay, p = 0.98, data = Orig_sample)[2]` minutes early.

```{r}
qdata( ~ arr_delay, p = 0.98, data = Orig_sample)
```

We can check the reliability of that estimate using bootstrapping.

```{r}
Bootstrap_trials <- do(500) *
  qdata(~arr_delay, p = 0.98,
         data = sample_n(Orig_sample, size = n, replace = TRUE))
favstats( ~ quantile, data = Bootstrap_trials)
BPCI <- quantile(Bootstrap_trials$quantile, prob = c(0.025, 0.975))
BPCI
ggplot(data = Bootstrap_trials, aes(x = quantile)) + 
  geom_histogram(fill = "peachpuff", color = "black") + 
  theme_bw()
```

The bootstrapped standard error is `r favstats( ~ quantile, data = Bootstrap_trials)[7]` minutes. The corresponding 95% confidence interval is `r favstats( ~ quantile, data = Bootstrap_trials)[6]` $\pm$ `r 2*favstats( ~ quantile, data = Bootstrap_trials)[7]` minutes. A policy based on this would be practically a shot in the dark: unlikely to hit the target.

One way to fix things might be to collect more data, hoping to get a more reliable estimate of the 98^_th_^ percentile. Let’s generate a sample with $n = 10,000$ cases.

```{r}
n <- 10000
new_sample <- SF %>% sample_n(size = n, replace = FALSE)
Bootstrap_trials <- do(2000) *
  qdata(~arr_delay, p = 0.98,
         data = sample_n(new_sample, size = n, replace = TRUE))
favstats( ~ quantile, data = Bootstrap_trials)
BPCI <- quantile(Bootstrap_trials$quantile, prob = c(0.025, 0.975))
BPCI
ggplot(data = Bootstrap_trials, aes(x = quantile)) + 
  geom_histogram(fill = "peachpuff", color = "black") + 
  theme_bw()
```

```{r}
# A much faster solution!
sims <- 2000
qs <- numeric(sims)
for(i in 1:sims){
  bss <- sample(new_sample$arr_delay, size = 10000, replace = TRUE)
  qs[i] <- quantile(bss, prob = 0.98)
}
CI <- quantile(qs, prob = c(0.025, 0.975))
CI
c(mean(qs), sd(qs), 2*sd(qs))
```

* * *

* I left the text the same but used inline code to insert the correct numbers...so, now the text will need to change...a confidence interval with a margin of error of 10 minutes is not bad? 

Disappointing! The 95% confidence interval is still very broad, `r round(mean(qs),2)` $\pm$ `r round(2*sd(qs),2)` minutes. The standard error of the 98^_th_^ percentile estimated from a sample of size $n = 10,000$ is not better. This is showing us that estimates of the 98^_th_^ percentile are not very reliable, since it is by definition in the tail of the distribution. Having more data doesn’t cure all ills. Knowing this, we might decide not to set our goal in terms of the unreliable 98^_th_^ percentile, or at least to tell our boss that there is no way to guarantee that the policy based on 98 percent will come close to meeting its goal. Or, even better, we might decide to examine things more closely, as in the next section.

**Comment by nicholasjhorton** [comment]
Apologies for the delay: this issue got lost.  I'll work to address your helpful suggestions.

**Comment by beanumber** [comment]
I believe this has been addressed in the 2nd edition. @nicholasjhorton can you confirm? 

https://beanumber.github.io/mdsr2e/ch-foundations.html#sec:boot

**Comment by nicholasjhorton** [comment]
That's correct: @alanarnholt thanks for your careful read and apologies for the delay.
