### ISSUE TITLE
Typo in Gramar of Graphics Exercises (website version)

### ISSUE THREAD

**Issue by homerhanumat** [mdsr-book/mdsr-book.github.io#17]
In the [Chapter 3 Exercises Rmd source](https://raw.githubusercontent.com/mdsr-book/mdsr-book.github.io/master/instructor/datavizII-ex.Rmd), replace LaTeX `\var` and `\emph` with their Markdown equivalents.

**Comment by beanumber** [comment]
Thanks @homerhanumat !
