### ISSUE TITLE
Broken Link in "Summarizing Groups" Lab

### ISSUE THREAD

**Issue by homerhanumat** [mdsr-book/mdsr-book.github.io#18]
In [https://raw.githubusercontent.com/mdsr-book/mdsr-book.github.io/master/instructor/lab-group_by.Rmd](https://raw.githubusercontent.com/mdsr-book/mdsr-book.github.io/master/instructor/lab-group_by.Rmd) the link to the Single Table Analysis lab is broken.

**Comment by beanumber** [comment]
Thanks @homerhanumat !
