### ISSUE TITLE
Info on Google Maps API Key

### ISSUE THREAD

**Issue by homerhanumat** [mdsr-book/mdsr-book.github.io#19]
In light of Google's recent requirement of a key to use its maps API, it might be worthwhile to post a tutorial on the MDSR site advising folks on what version of **ggmap** to install for the time being, how to obtain and register the key, etc., as per [#51](https://github.com/dkahle/ggmap/issues/51) on the **ggmap** Github repo.  Perhaps also reference the tutorial in the next printing?

**Comment by beanumber** [comment]
OK, thanks for the good ideas. 

If there is a 2nd edition, `ggmap` will likely go away altogether, since `ggplot2` now supports `geom_sf()` natively.

**Comment by beanumber** [comment]
Indeed, `ggmap` is dead. Love live `ggspatial`!
