### ISSUE TITLE
Post More Textbook Code on the Site?

### ISSUE THREAD

**Issue by homerhanumat** [mdsr-book/mdsr-book.github.io#20]
The [Online Supplements](https://mdsr-book.github.io/instructor.html#online_supplements) are very useful for instructors, especially when they contain the code used for a given chapter.  Would it be possible to post code for the remaining chapters? It seems a bit much to make instructors (and/or students) re-type extended wrangling code, e.g., for the `cars` data in section 9.1.

**Comment by beanumber** [comment]
Great idea. I will do this.

**Comment by beanumber** [comment]
Done. (http://mdsr-book.github.io/instructor.html)
