### ISSUE TITLE
page 335:  district variable in district elections requires additonal mutation for successful merge of nc_results with nc_shp

### ISSUE THREAD

**Issue by homerhanumat** [mdsr-book/mdsr-book.github.io#21]
In Section 14.4 on Congressional Districts, the values of the variable `district` in the table `nc_results` are: 01, 02, ..., 12, 13, whereas in the (latest?) downloads from UCLA the  values of the variable `DISTRICT` in the table `nc_shp@data` end up being 1, 2, ..., 12, 13.

As a result data is lost in the creation of `nc_merged`.

Perhaps create the table `district_elections` with one additional call to `mutate()`, as follows:

```
district_elections <-
  he %>% 
  mutate(district = stringr::str_sub(district, start = 1, end = 2)) %>% 
  mutate(district = stringr::str_replace(district, "^0", "")) %>% 
  group_by(state, district) %>% 
  summarize(N = n(),
            total_votes = sum(general_votes, na.rm = TRUE),
            d_votes = sum(ifelse(party == "D", general_votes, 0)),
            r_votes = sum(ifelse(party == "R", general_votes, 0))) %>% 
  mutate(other_votes = total_votes - d_votes - r_votes,
         r_pct = r_votes / total_votes,
         r_win = r_votes > d_votes)
```

**Comment by homerhanumat** [comment]
Actually there might be no issue:  I used `fec::house_elections_2012` rather than pulling from the database.

**Comment by homerhanumat** [comment]
I now see that the Smith College fec database has the 2016 results, but still the same 01, 02, ... numbering of districts, so the issue stands.

**Comment by beanumber** [comment]
We're now using the `fec12` package for this:

https://github.com/baumer-lab/fec12
