### ISSUE TITLE
.png Files in Supplementary Exercises

### ISSUE THREAD

**Issue by wmharris** [mdsr-book/mdsr-book.github.io#23]
In working through the online edition of MDSR 2nd edition, I noticed that .png files for Supplementary Exercises are not rendering. This has happened to me in looking at Chapters 2-6--it could hold true for other chapters as well. The issue was present in both Firefox and Chrome browsers.

**Comment by beanumber** [comment]
Confirmed. It looks like the paths to the images are wrongly including local paths. 

I will investigate -- thanks for pointing this out @wmharris

**Comment by bddavison** [comment]
Bump

**Comment by KoreanJordan** [comment]
Bump

**Comment by beanumber** [comment]
The problem persists in the 3rd edition, and is covered by https://github.com/mdsr-book/mdsr3e/issues/49
