### ISSUE TITLE
Section B.2 in the Left TOC Appears Incorrectly. 

### ISSUE THREAD

**Issue by jrozra200** [mdsr-book/mdsr-book.github.io#26]
Here is a picture of how the TOC shows up to me. Note the `(ref:R)`.

![Screen Shot 2022-01-05 at 4 02 44 PM](https://user-images.githubusercontent.com/9554768/148289147-204771c6-ebaf-4b41-afbb-453164fbdcd4.png)

The title of the section in main column is correct in appearance: 

![Screen Shot 2022-01-05 at 4 02 50 PM](https://user-images.githubusercontent.com/9554768/148289129-069656d8-df53-413d-b5d8-3907c98ef304.png)

Finally - A link for reference: https://mdsr-book.github.io/mdsr2e/ch-R.html#learning-refr

**Comment by nicholasjhorton** [comment]
@jrozra200 thanks for submitting this issue. We do know that there are some places where bookdown doesn't appropriately process formatting commands (like these references) on the html version (though it works on the pdf). We will try to come up with a fix.
