### ISSUE TITLE
missing link/reference/image in tidy data chapter

### ISSUE THREAD

**Issue by nickreich** [mdsr-book/mdsr-book.github.io#28]
https://mdsr-book.github.io/mdsr2e/ch-dataII.html#motivation

![image](https://user-images.githubusercontent.com/1280767/150002254-fe0a67e6-f8cf-498c-99a2-7cbdcfc1c3ee.png)

**Comment by nicholasjhorton** [comment]
Thanks for pointing this out. Unfortunately, some of the bookdown pdf markup doesn't yet work in the html version. We will work to fix this at our next iteration.

**Comment by beanumber** [comment]
This seems to be fixed in the 3rd edition:

https://mdsr-book.github.io/mdsr3e/06-dataII.html#motivation
