### ISSUE TITLE
use guide="none" instead of guide=FALSE

### ISSUE THREAD

**Issue by nickreich** [mdsr-book/mdsr-book.github.io#33]
I see this warning in a few places:
```
Warning: It is deprecated to specify `guide = FALSE` to remove a guide.
Please use `guide = "none"` instead.
```

e.g. section 3.3.1  https://mdsr-book.github.io/mdsr2e/ch-vizII.html#percentage-of-people-alive-today
![image](https://user-images.githubusercontent.com/1280767/153269412-b9be5da3-d799-4d13-95a1-8f869487cb94.png)

**Comment by beanumber** [comment]
Thanks @nickreich !

**Comment by beanumber** [comment]
This has been fixed in the 3rd edition.
