### ISSUE TITLE
Awkward sentence about NYC flights

### ISSUE THREAD

**Issue by bddavison** [mdsr-book/mdsr-book.github.io#34]
In Section 5.2, talking about left_join(), the book says "Suppose that we are only interested in flights from the New York City airports on the West Coast."  This is awkward as it sounds like there are New York CIty airports on the West Coast.  Cleaner would be to say "Suppose that we are only interested in flights from New York City airports to the West Coast."

**Comment by beanumber** [comment]
Yup. That's a typo. Thanks @bddavison !
