### ISSUE TITLE
Classifier is misspelled in Chapter 8.4.4

### ISSUE THREAD

**Issue by jrozra200** [mdsr-book/mdsr-book.github.io#36]
There are a few cases in which "classifier" is spelled "classifer" (missing the i) in chapter 8. 

> 8.4.4 Race prediction
> Imai and Khanna (2016) built a racial prediction algorithm using a Bayes **classifer** (see Section [11.1.4](https://mdsr-book.github.io/mdsr2e/ch-learningI.html#sec:bayes)) trained on voter registration records from Florida and the U.S. Census Bureau’s name list. In addition to the publishing the paper detailing the methodology, the authors published the software for the **classifer** on [GitHub](https://en.wikipedia.org/w/index.php?search=GitHub) under an open-source license. The wru package is available on CRAN and will return predicted probabilities for a person’s race based on either their last name alone, or their last name and their address.

**Comment by beanumber** [comment]
Thanks for pointing these out!

**Comment by nicholasjhorton** [comment]
Thanks for the report! The fix is in and should show up later today at
https://mdsr-book.github.io/mdsr3e/08-ethics.html

https://github.com/mdsr-book/mdsr3e/commit/aa7eebb768726bbefaa95193e55cd709c755e2d4
