### ISSUE TITLE
Slugging Percentage (SLG) formule

### ISSUE THREAD

**Issue by Tolstik2004** [mdsr-book/mdsr-book.github.io#39]
Chapter 5 Data wrangling on multiple tables. 
5.3 Extended example: Manny Ramirez.
Slugging Percentage (SLG).
In the code to calculate Manny Ramirez's SLG, the following formula is used:  "SLG = sum(H + X2B + 2 * X3B + 3 * HR) / sum(AB)". According to the MLB glossary, the SLG formula is : SLG= (1B + 2Bx2 + 3Bx3 + HRx4)/AB, so in your code the correct form should be: "SLG = sum(H + 2 * X2B + 3 * X3B + 4 * HR) / sum(AB)".Can you please check this formula? Thank you.

**Comment by beanumber** [comment]
No, you'd be double-counting extra base hits, because $H = 1B + 2B + 3B + HR$, so $(1B + 2 \cdot 2B + 3 \cdot 3B + 4 \cdot HR) = (H + 2B + 2 \cdot 3B + 3 \cdot HR)$.

**Comment by Tolstik2004** [comment]
I got it, thanks

**Comment by nicholasjhorton** [comment]
If it's any consolation I asked the *exact* same question a number of years ago.

In any case, best wishes for the start of the 2023 baseball season!
