### ISSUE TITLE
PDF version of the book?

### ISSUE THREAD

**Issue by liar666** [mdsr-book/mdsr-book.github.io#40]
Hi,

Thanks for the very good book. I was wondering if you were planning to release a PDF version of the book ?

I often read book while in the subway or train, with no internet connectivity. Also reading online means re-downloading the book everytime we access it. This is far from eco-friendly :( 

Also, with PDFs, I can use TTS apps to read the book aloud for me. Helps me read very fast. Neat!

Cheers

**Comment by beanumber** [comment]
Glad you're enjoying the book!

Sadly, I don't think our agreement with the publisher allows for this.
