### ISSUE TITLE
lubridate does not need to be loaded

### ISSUE THREAD

**Issue by willwerscheid** [mdsr-book/mdsr-book.github.io#41]
I am reading chapter 4; I believe `lubridate` is now loaded as a core Tidyverse package, so `library(lubridate)` and `lubridate::` could be removed. (Not a bug but in my opinion one fewer package for students to have to remember would be a good thing.)

**Comment by beanumber** [comment]
Confirmed. 

https://mdsr-book.github.io/mdsr3e/04-dataI.html

It should be easy enough to remove the unnecessary calls to `lubridate`.

**Comment by beanumber** [comment]
Closed via https://github.com/mdsr-book/mdsr3e/commit/3e863dfe1861aebc0da906d7d112faaf77e32025

**Comment by nicholasjhorton** [comment]
Thanks!
