### ISSUE TITLE
Minor edits in Section 5.4

### ISSUE THREAD

**Issue by willwerscheid** [mdsr-book/mdsr-book.github.io#50]
Max Marchi and Jim Albert link to a Wikipedia search for them but no Wikipedia pages exist. Maybe just remove the links? Cleveland Indians should be Cleveland Guardians (Marchi is still with the org, at least according to LinkedIn).

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/mdsr-book/mdsr3e/commit/ac91412e23db53c654a60872fdd356521cb2125a

Thanks for alerting us to the issues!
