### ISSUE TITLE
EOCE 2.6

### ISSUE THREAD

**Issue by andrewpbray** [mdsr-book/mdsr-book.github.io#9]
Several students were not able to get this graphic to load. Pretty sure it had to do with browser settings and javascript. Not sure if there is any way you can nip this in the bud. Maybe a disclaimer in the preface about the interactive graphics components?

**Comment by beanumber** [comment]
Huh. Can they view the static image even if the rollover part doesn't work?

**Comment by andrewpbray** [comment]
Nope, apparently no static image there. I don't have a sense of how widespread this issue is, though.

**Comment by beanumber** [comment]
We still have the exercise. I hope this doesn't persist.
